// 150 daily rotating phrases for the dashboard subheader.
// Cycles based on day-of-year so every day shows a new one.
export const DAILY_PHRASES: string[] = [
  "Another day, another firm funded. Let's go. 🚀",
  "Coffee in, deals out. ☕",
  "Great day to turn a maybe into a yes. 💪",
  "Your firms. Your files. Your win column. 🏆",
  "Small steps, signed contracts. ✍️",
  "Deals don't move themselves. You do. 🛠️",
  "Make today annoyingly productive. 🐝",
  "Pick one hard thing. Do it first. 🥇",
  "Funded files love a fresh start. 💸",
  "Be the reason a firm gets paid this week. 🤝",
  "Tiny wins compound. Keep stacking. 📈",
  "You miss 100% of the calls you don't make. 📞",
  "Today's tasks > yesterday's excuses.",
  "Approvals taste better with follow-ups. 🍰",
  "Show your to-do list who's boss. 👔",
  "Good outcomes start with good check-ins. ✅",
  "A clean dashboard is a calm mind. 🧘",
  "Reach out before they ghost. 👻",
  "Notes today, miracles tomorrow. 📝",
  "Be relentlessly helpful. 🌟",
  "Close the loop. Every loop. 🔁",
  "Quiet files hide loud problems. 🔍",
  "Make the next call your best call. 🎯",
  "Funded is a feeling. Go get it. 💚",
  "Hustle softly, follow up loudly. 📣",
  "Your future self says thanks for updating that note. 🙏",
  "One more call. Always one more call. ☎️",
  "Build trust like it's the only KPI. 🤲",
  "Action beats anxiety every time. ⚡",
  "Be the team's favorite teammate today. 🫶",
  "Read the room. Then read the file. 📂",
  "Move fast. Care more. Both win. 🏎️",
  "Underpromise. Overdeliver. Repeat. 🔂",
  "Don't let a good lead go cold. 🔥",
  "Tiny improvements all day long. 📐",
  "Be the calm in a chaotic intake. 🌊",
  "Energy is contagious. Spread the good kind. ✨",
  "Slow is smooth. Smooth is funded. 🧈",
  "Done is the most beautiful word. 🎀",
  "Show up like the firm is counting on you. (They are.) 🫡",
  "Send the email you've been putting off. 📨",
  "Curiosity closes more deals than scripts. 🧠",
  "Be specific. Vague kills momentum. 🎯",
  "Make today look easy. (It's not. You're just good.) 💁",
  "Bring snacks. Bring solutions. 🥨",
  "Confidence is a follow-up away. 📲",
  "If it matters, write it down. 🗒️",
  "Patience pays. Persistence funds. 💰",
  "Be the email people actually want to open. 💌",
  "Stop refreshing. Start reaching out. 🔄",
  "The best time to update a status was yesterday. The second best is now. ⏰",
  "Tiny details. Huge outcomes. 🔬",
  "Be kind. It's also good for business. 💚",
  "Win the first hour, win the rest. 🌅",
  "Treat every firm like your favorite firm. 🏛️",
  "Move with purpose, not panic. 🎈",
  "Every 'no' is a 'next.' ➡️",
  "Today's hustle is tomorrow's funded file. 🛤️",
  "Be the dot that connects the dots. 🔗",
  "Ship the update. Send the recap. 🚢",
  "Make the boring stuff legendary. 🦄",
  "Optimism is a strategy. Try it. 🌞",
  "Be hard to ignore, easy to work with. 🧲",
  "Less explaining, more delivering. 📦",
  "Clear the list, clear the head. 🧹",
  "Bring receipts. Always bring receipts. 🧾",
  "Don't just close — close cleanly. ✨",
  "You've got this. Like, mathematically. ➗",
  "Trust the process, but verify the data. 🔎",
  "Be the easiest 'yes' a firm gets all week. 👍",
  "Tend the deals. The deals tend to you. 💎",
  "Send the doc. Make the call. Win the day. 🏆",
  "It's a great day to over-communicate. 🗣️",
  "Solve before they ask. 🪄",
  "The best follow-up is the one you actually do. ✔️",
  "Be brief. Be useful. Be memorable. ✨",
  "Small fires, fast water. 🪣",
  "Be a thermostat, not a thermometer. 🌡️",
  "Make today a 'funds wired' kind of day. 💵",
  "Friendly persistence is a superpower. 🦸",
  "Move one deal forward. Then another. 🚂",
  "Less doom-scrolling. More deal-closing. 📊",
  "Reply quickly. Reply kindly. Reply now. 💬",
  "Don't let perfect block 'sent.' 📤",
  "Be the person who actually reads the notes. 👀",
  "Inbox zero is a vibe. Funded files are better. 💼",
  "Lead with empathy. Close with clarity. 🫂",
  "Be the reason this place runs well. ⚙️",
  "Momentum beats motivation. Every time. 🛼",
  "Calls before lunch. Always. 🍱",
  "If in doubt, update the file. 📋",
  "Start with the task you'd rather avoid. 🧗",
  "Be the standard, not the exception. ⭐",
  "Make the handoff a hug, not a hand grenade. 💣→🤗",
  "Write notes future-you will thank you for. 📚",
  "Bias toward action. Always. ⏩",
  "One tiny update can unblock the whole team. 🔓",
  "Preparation always gets paid back. 🎒",
  "Today's quiet work is tomorrow's loud win. 📢",
  "Win the next 10 minutes. Repeat. ⏱️",
  "Be precise. Vague slows everyone down. 🎯",
  "Make a firm's day. It'll make yours back. 🔄",
  "Show up. Step up. Follow up. 👔",
  "Be the message they were hoping to get. 💌",
  "Energy first. Edits later. ⚡",
  "Take the meeting. Then take the win. 🏅",
  "One thoughtful note beats ten generic ones. ✨",
  "Outwork your worries. 💪",
  "Be useful at speed. ⚡",
  "Funded files don't fund themselves. 🛠️",
  "A great recap is a love letter to your team. 💌",
  "Treat every call like it might be the one. 🎰",
  "Be early. Be ready. Be relentless. 🌄",
  "If it'll take 2 minutes, do it now. ⏲️",
  "Be the dashboard's favorite user today. 🥰",
  "Follow up so often it's almost weird. (Almost.) 😄",
  "Set the tone. Set the pace. Set the meeting. 📆",
  "Be impossible to disappoint. 🛡️",
  "Make the spreadsheet sing. 🎶",
  "Bring quiet excellence to loud problems. 🔇",
  "Be ridiculously responsive. 📩",
  "Make today's call the one they remember. 🧠",
  "Move the file. Move the world. 🌍",
  "Today, be 1% better at one specific thing. ➕",
  "Be the team's secret weapon. 🗡️",
  "Don't wait for clarity. Create it. 🔦",
  "A great update beats a perfect plan. 📝",
  "Be the person who closes the tabs AND the deals. 🪟",
  "Soft skills, hard results. 🤝",
  "Be the proof that prep wins. 🏗️",
  "Win one. Note one. Move one. 🔁",
  "Make 'follow up' your love language. 💞",
  "Take the boring win. They count too. 🏆",
  "Funded today, funded forever. (In our hearts.) ❤️",
  "Make today suspiciously smooth. 🧴",
  "Outlast the awkward pause. They'll talk first. 🤫",
  "Be the calmest person in the chat. 🧘",
  "Tiny act of kindness > big email blast. 💐",
  "Speed wins. Sloppy loses. ⚡",
  "Be the team member you'd want to have. 🫶",
  "Send the recap. They'll love you for it. 💌",
  "Get curious about the 'no.' 🤔",
  "Make the next 10 minutes count. ⏳",
  "Quiet confidence. Loud results. 🔊",
  "Be the human in the inbox. 🫀",
  "Friendly + fast + accurate = unstoppable. 🌪️",
  "Be the person who makes everyone else look good. 🌟",
  "Today's good habit is tomorrow's quiet superpower. 🦸",
  "Don't just hit quota — care about the file. 💚",
  "Lead with the answer. Then explain. 🥇",
  "Make today the day someone says 'thank you.' 🙏",
  "Show up like it matters. (It does.) ✨",
  "And… one more call. ☎️",
];

export function getDailyPhrase(date: Date = new Date()): string {
  const start = Date.UTC(date.getUTCFullYear(), 0, 0);
  const diff = Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate()) - start;
  const dayOfYear = Math.floor(diff / 86400000);
  // Mix in year so Jan 1 isn't always phrase #1
  const idx = (dayOfYear + date.getUTCFullYear() * 7) % DAILY_PHRASES.length;
  return DAILY_PHRASES[idx];
}
